In [6]:
import collections
import torch
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
import numpy as np
import random
import math
import torch.nn as nn

device = torch.device('cuda')

# load file

In [7]:
# data: Penn Tree Bank, sampled from Wall Street Journal articles.
# each line = a sentence

with open('/home/tian/Projects/d2l/data/ptb/ptb.train.txt', 'r') as f:
    raw_train_text = f.read()

raw_train_text = raw_train_text.split('\n') # num_line, num_words_per_line
raw_train_text = [line.split() for line in raw_train_text]

In [8]:
print(raw_train_text[:5])

[['aer', 'banknote', 'berlitz', 'calloway', 'centrust', 'cluett', 'fromstein', 'gitano', 'guterman', 'hydro-quebec', 'ipo', 'kia', 'memotec', 'mlx', 'nahb', 'punts', 'rake', 'regatta', 'rubens', 'sim', 'snack-food', 'ssangyong', 'swapo', 'wachter'], ['pierre', '<unk>', 'N', 'years', 'old', 'will', 'join', 'the', 'board', 'as', 'a', 'nonexecutive', 'director', 'nov.', 'N'], ['mr.', '<unk>', 'is', 'chairman', 'of', '<unk>', 'n.v.', 'the', 'dutch', 'publishing', 'group'], ['rudolph', '<unk>', 'N', 'years', 'old', 'and', 'former', 'chairman', 'of', 'consolidated', 'gold', 'fields', 'plc', 'was', 'named', 'a', 'nonexecutive', 'director', 'of', 'this', 'british', 'industrial', 'conglomerate'], ['a', 'form', 'of', 'asbestos', 'once', 'used', 'to', 'make', 'kent', 'cigarette', 'filters', 'has', 'caused', 'a', 'high', 'percentage', 'of', 'cancer', 'deaths', 'among', 'a', 'group', 'of', 'workers', 'exposed', 'to', 'it', 'more', 'than', 'N', 'years', 'ago', 'researchers', 'reported']]


# Subsampling, getting subsampled vocab and corpus

In [9]:
class ptbVocab:
    def __init__(self, raw_text, min_freq):
        self.n_sentences = len(raw_text)
        raw_text_flatten = [w for line in raw_text for w in line]
        counter = collections.Counter(raw_text_flatten)
        print(f'The original #vocab: {len(counter)}')

        # any word that appears less than 10 times is replaced by the “<unk>” token
        min_freq_text = []
        min_freq_text_flatten = []
        for line in raw_text:
            new_line = []
            for word in line:
                if counter[word] < min_freq:
                    new_line.append('<unk>')
                else:
                    new_line.append(word)
            min_freq_text.append(new_line)
            min_freq_text_flatten.extend(new_line)

        print(f'After discarded freq < {min_freq}, #vocab: {len(set(min_freq_text_flatten))}')

        counter_after_min_freq = collections.Counter(min_freq_text_flatten)
        
        # subsampling to possibly discard the words with high freq like "a", "the"... do not interfere the #vocab
        def keep(token):
            return(random.uniform(0, 1) < math.sqrt(1e-4 / counter_after_min_freq[token] * len(min_freq_text_flatten)))
        self.text_subsampled = [[token for token in line if keep(token)] for line in min_freq_text]
        self.text_subsampled_flatten = [w for line in self.text_subsampled for w in line]
        self.n_words_subsampled = len(self.text_subsampled_flatten)
        print(f'After subsampled, the #vocab: {len(set(self.text_subsampled_flatten))}')
        print(f'The original #words: {len(raw_text_flatten)}\nThe new #words: {len(self.text_subsampled_flatten)}')
        self.counter = counter_after_min_freq


In [10]:
train_vocab = ptbVocab(raw_train_text, 10)

The original #vocab: 9999
After discarded freq < 10, #vocab: 6719
After subsampled, the #vocab: 6719
The original #words: 887521
The new #words: 354036


In [11]:
vocab_c = train_vocab.counter
vocab_c = list(vocab_c.keys())

# make the <unk> to 0
if vocab_c[0] != '<unk>':
    replaced_word = vocab_c[0]
    for i, word in enumerate(vocab_c):
        if word == '<unk>':
            break
    
    vocab_c[i] = vocab_c[0]
    vocab_c[0] = '<unk>'


vocab_word_to_id = {}
vocab_id_to_word = {}
for idx, word in enumerate(vocab_c):
    vocab_word_to_id[word] = idx
    vocab_id_to_word[idx] = word

In [12]:
vocab_id_to_word[0]

'<unk>'

In [13]:
corpus = []
for line in train_vocab.text_subsampled:
    l = []
    for word in line:
        l.append(vocab_word_to_id[word])

    corpus.append(l)

In [14]:
len(corpus) == train_vocab.n_sentences

True

# Extracting center words and context words

In [15]:
def get_centers_and_contexts(corpus, max_window_size):
    """Return center words and context words in skip-gram."""
    centers, contexts = [], []
    for line in corpus:
        # To form a "center word--context word" pair, each sentence needs to
        # have at least 2 words
        if len(line) < 2:
            continue
        centers += line
        for i in range(len(line)):  # Context window centered at `i`
            window_size = random.randint(1, max_window_size)
            indices = list(range(max(0, i - window_size),
                                 min(len(line), i + 1 + window_size)))
            # Exclude the center word from the context words
            indices.remove(i)
            contexts.append([line[idx] for idx in indices])
    return centers, contexts

In [16]:
tiny_dataset = [list(range(7)), list(range(7, 10))]
print('dataset', tiny_dataset)
for center, context in zip(*get_centers_and_contexts(tiny_dataset, 4)):
    print('center', center, 'has contexts', context)

dataset [[0, 1, 2, 3, 4, 5, 6], [7, 8, 9]]
center 0 has contexts [1, 2, 3]
center 1 has contexts [0, 2]
center 2 has contexts [1, 3]
center 3 has contexts [0, 1, 2, 4, 5, 6]
center 4 has contexts [0, 1, 2, 3, 5, 6]
center 5 has contexts [3, 4, 6]
center 6 has contexts [4, 5]
center 7 has contexts [8, 9]
center 8 has contexts [7, 9]
center 9 has contexts [7, 8]


In [17]:
all_centers, all_contexts = get_centers_and_contexts(corpus, 5)
f'# center-context pairs: {sum([len(contexts) for contexts in all_contexts])}'

'# center-context pairs: 1560241'

In [18]:
len(all_centers) == len(all_contexts)

True

In [19]:
vocab_word_to_id['<unk>']

0

# Negative sampling

In [20]:
class RandomGenerator:
    """Randomly draw among {1, ..., n} according to n sampling weights."""
    def __init__(self, sampling_weights):
        # Exclude
        self.population = list(range(1, len(sampling_weights) + 1))
        self.sampling_weights = sampling_weights
        self.candidates = []
        self.i = 0

    def draw(self):
        if self.i == len(self.candidates):
            # Cache `k` random sampling results
            self.candidates = random.choices(
                self.population, self.sampling_weights, k=10000)
            self.i = 0
        self.i += 1
        return self.candidates[self.i - 1]

In [21]:
generator = RandomGenerator([2, 3, 4])
[generator.draw() for _ in range(10)]

[3, 2, 3, 3, 3, 3, 2, 3, 3, 3]

In [22]:
def get_negatives(all_contexts, id_to_word, counter, K):
    """Return noise words in negative sampling."""
    # Sampling weights for words with indices 1, 2, ... (index 0 is the excluded unknown token) in the vocabulary
    sampling_weights = [counter[id_to_word[i]]**0.75
                        for i in range(1, len(id_to_word))]
    all_negatives, generator = [], RandomGenerator(sampling_weights)
    for contexts in all_contexts:
        negatives = []
        while len(negatives) < len(contexts) * K:
            neg = generator.draw()
            # Noise words cannot be context words
            if neg not in contexts:
                negatives.append(neg)
        all_negatives.append(negatives)
    return all_negatives

all_negatives = get_negatives(all_contexts, vocab_id_to_word, train_vocab.counter, 5)

# Dataset and DataLoader

In [23]:
class PTBDataset(Dataset):
    def __init__(self, centers, contexts, negatives):
        assert len(centers) == len(contexts) == len(negatives)
        self.centers = centers
        # self.contexts = [line+[0]*(max_window_size-len(line)) for line in contexts if len(line)<max_window_size]
        self.contexts = contexts
        # self.negatives = [line+[0]*(max_window_size-len(line)) for line in contexts if len(line)<max_window_size]
        self.negatives = negatives

    def __getitem__(self, index):
        # center = torch.tensor(self.centers[index])
        
        return (self.centers[index], self.contexts[index], self.negatives[index])
    
    def __len__(self):
        return len(self.centers)
    

In [24]:
# for every batch, do these

def batchify(data):
    """Return a minibatch of examples for skip-gram with negative sampling."""
    max_len = max(len(c) + len(n) for _, c, n in data)
    centers, contexts_negatives, masks, labels = [], [], [], []
    for center, context, negative in data:
        cur_len = len(context) + len(negative)
        centers += [center]
        contexts_negatives += [context + negative + [0] * (max_len - cur_len)]
        masks += [[1] * cur_len + [0] * (max_len - cur_len)]
        labels += [[1] * len(context) + [0] * (max_len - len(context))]
    return (torch.tensor(centers).reshape((-1, 1)), torch.tensor(
        contexts_negatives), torch.tensor(masks), torch.tensor(labels))

In [25]:
x_1 = (1, [2, 2], [3, 3, 3, 3])
x_2 = (1, [2, 2, 2], [3, 3, 3, 3, 3, 3])
batch = batchify((x_1, x_2))

names = ['centers', 'contexts_negatives', 'masks', 'labels']
for name, data in zip(names, batch):
    print(name, '=', data)

centers = tensor([[1],
        [1]])
contexts_negatives = tensor([[2, 2, 3, 3, 3, 3, 0, 0, 0],
        [2, 2, 2, 3, 3, 3, 3, 3, 3]])
masks = tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])
labels = tensor([[1, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 0, 0, 0]])


In [26]:
# from raw_text to training_dataset

train_vocab = ptbVocab(raw_train_text, 10)

vocab_c = train_vocab.counter
vocab_c = list(vocab_c.keys())

# make the <unk> to 0
if vocab_c[0] != '<unk>':
    replaced_word = vocab_c[0]
    for i, word in enumerate(vocab_c):
        if word == '<unk>':
            break
    
    vocab_c[i] = vocab_c[0]
    vocab_c[0] = '<unk>'

vocab_word_to_id = {}
vocab_id_to_word = {}
for a, b in enumerate(vocab_c):
    vocab_word_to_id[b] = a
    vocab_id_to_word[a] = b


corpus = []
for line in train_vocab.text_subsampled:
    l = []
    for word in line:
        l.append(vocab_word_to_id[word])

    corpus.append(l)


all_centers, all_contexts = get_centers_and_contexts(corpus, 5)

all_negatives = get_negatives(all_contexts, vocab_id_to_word, train_vocab.counter, 5)

The original #vocab: 9999
After discarded freq < 10, #vocab: 6719
After subsampled, the #vocab: 6719
The original #words: 887521
The new #words: 354295


In [27]:
batch_size = 512

train_data = PTBDataset(centers=all_centers, contexts=all_contexts, negatives=all_negatives)
train_dataloader = DataLoader(dataset=train_data, batch_size=batch_size, shuffle=True, collate_fn=batchify, num_workers=4)

# For every batch_size: (0: center_word, 1: context+negative_sample, 2: mask, 3: label)
# label: if it is the context

In [28]:
a = iter(train_dataloader)
b = next(a)
print(f'{b[1][0]}\n{b[2][0]}\n{b[3][0]}')

tensor([ 299,  120,  302,  636,   77, 1187,  341,    1, 3052, 1664,  633, 2678,
         349, 4497, 2786,  457, 4947,   36,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


# Model

Skipgram: input: context, output: center_word

In [29]:
# forward() can have only one input

class skip_gram(nn.Module):
      def __init__(self, vocab_size, hidden_size=100):
            super(skip_gram, self).__init__()
            self.embed1= nn.Embedding(num_embeddings=vocab_size, embedding_dim=hidden_size)
            def init_weights(module):
                  if type(module) == nn.Embedding:
                        nn.init.xavier_uniform_(module.weight)
            self.embed1.apply(init_weights)

      def forward(self, x):
            x = self.embed1(x)
            return x

In [30]:
center_model = skip_gram(vocab_size=len(vocab_id_to_word)).to(device)
context_model = skip_gram(vocab_size=len(vocab_id_to_word)).to(device)

In [31]:
a = iter(train_dataloader)
center, context_negaive, mask, label = next(a)
center = center.to(device)
context_negaive = context_negaive.to(device)

In [32]:
context_negaive.shape, center.shape

(torch.Size([512, 60]), torch.Size([512, 1]))

In [33]:
center_model(center).shape

torch.Size([512, 1, 100])

In [34]:
context_model(context_negaive).permute(0,2,1).shape

torch.Size([512, 100, 60])

In [35]:
torch.bmm(center_model(center), context_model(context_negaive).permute(0,2,1))[0][0]
# 512, 60

tensor([ 4.9169e-04, -9.0279e-04, -8.1946e-04, -2.4383e-03,  9.6187e-03,
        -2.1166e-03,  1.4041e-03,  2.2078e-03, -2.3141e-06, -2.1227e-03,
         6.7155e-04,  4.2515e-03, -3.5466e-03,  3.4282e-03, -7.1935e-04,
         7.3398e-04,  5.9924e-04,  2.6551e-03,  4.5462e-03, -3.2659e-03,
        -1.2432e-03, -2.6723e-03, -5.4060e-04,  1.7929e-03,  8.0233e-04,
         8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,
         8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,
         8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,
         8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,
         8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,
         8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,
         8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04,  8.0233e-04],
       device='cuda:0', grad_fn=<SelectBackward0>)

# Training

In [42]:
# hyperparameter (batch_size in Dataset and DataLoader)
num_epochs = 50
learning_rate = 0.01

In [43]:
#loss function
class SigmoidBCELoss(nn.Module):
    # Binary cross-entropy loss with masking
    def __init__(self):
        super().__init__()

    def forward(self, inputs, target, mask=None):
        inputs = inputs.float() # the nn.functional.binary_cross_entropy_with_logits() expects a float input
        target = target.float() # the nn.functional.binary_cross_entropy_with_logits() expects a float input
        out = nn.functional.binary_cross_entropy_with_logits(
            inputs, target, weight=mask, reduction="none")
        out = out.mean(dim=1)
        out = out * mask.shape[1] / mask.sum(axis=1)
        return out

criterion = SigmoidBCELoss()    # This loss combines a Sigmoid layer and the BCELoss in one single class.
optimizer = torch.optim.Adam(list(center_model.parameters()) + list(context_model.parameters()), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=2, gamma=0.1)

In [44]:
pred = torch.tensor([[1.1, -2.2, 3.3, -4.4]] * 2)
label = torch.tensor([[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0]])
mask = torch.tensor([[1, 1, 1, 1], [1, 1, 0, 0]])
criterion(pred, label, mask=mask)

tensor([0.9352, 1.8462])

In [45]:
# an uneffective way to implement BCELoss
def sigmd(x):
    return -math.log(1 / (1 + math.exp(-x)))

print(f'{(sigmd(1.1) + sigmd(2.2) + sigmd(-3.3) + sigmd(4.4)) / 4:.4f}')
print(f'{(sigmd(-1.1) + sigmd(-2.2)) / 2:.4f}')

0.9352
1.8462


In [46]:
n_iter = len(train_dataloader)

In [47]:
for epoch in range(num_epochs):
    for i, (center, context_negaive, mask, label) in enumerate(train_dataloader):
        center = center.to(device)
        context_negaive = context_negaive.to(device)
        mask = mask.to(device)
        label = label.to(device)

        v = center_model(center)
        u = context_model(context_negaive)
        pred = torch.bmm(v, u.permute(0, 2, 1))


        loss = criterion(pred.reshape(label.shape), label, mask)
        optimizer.zero_grad()
        loss.sum().backward()
        optimizer.step()

        if (i+1) % (batch_size // 50) == 0 or (i+1) == batch_size:
            print(f'Epoch {epoch+1} / {num_epochs}: {i+1} / {n_iter} loss = {loss.sum().item()}')

    scheduler.step()


Epoch 1 / 50: 10 / 690 loss = 177.42721557617188
Epoch 1 / 50: 20 / 690 loss = 173.85028076171875
Epoch 1 / 50: 30 / 690 loss = 182.2039794921875
Epoch 1 / 50: 40 / 690 loss = 182.60372924804688
Epoch 1 / 50: 50 / 690 loss = 177.4052734375
Epoch 1 / 50: 60 / 690 loss = 174.39422607421875
Epoch 1 / 50: 70 / 690 loss = 181.46774291992188
Epoch 1 / 50: 80 / 690 loss = 180.83102416992188
Epoch 1 / 50: 90 / 690 loss = 178.4469757080078
Epoch 1 / 50: 100 / 690 loss = 183.5026397705078
Epoch 1 / 50: 110 / 690 loss = 179.52828979492188
Epoch 1 / 50: 120 / 690 loss = 182.5880126953125
Epoch 1 / 50: 130 / 690 loss = 184.68064880371094
Epoch 1 / 50: 140 / 690 loss = 183.31695556640625
Epoch 1 / 50: 150 / 690 loss = 184.8416290283203
Epoch 1 / 50: 160 / 690 loss = 183.24435424804688
Epoch 1 / 50: 170 / 690 loss = 182.49099731445312
Epoch 1 / 50: 180 / 690 loss = 186.93397521972656
Epoch 1 / 50: 190 / 690 loss = 184.79986572265625
Epoch 1 / 50: 200 / 690 loss = 185.76841735839844
Epoch 1 / 50: 210 

# Inference

In [51]:
center_model.eval()
context_model.eval()


skip_gram(
  (embed1): Embedding(6719, 100)
)

In [61]:
center_model.embed1.weight.data

tensor([[ 0.1360, -0.0591,  0.0454,  ..., -0.0315, -0.1826,  0.0366],
        [ 0.0560, -0.0232, -0.0131,  ...,  0.1970, -0.1406, -0.1616],
        [-0.3922,  0.0974,  0.0030,  ...,  0.0766, -0.5292, -0.2426],
        ...,
        [-0.6992, -0.9341,  1.0671,  ..., -0.5652,  0.0323, -0.1671],
        [ 0.1874, -0.2392,  0.6160,  ...,  0.0471,  0.1257,  0.0911],
        [ 0.7014, -0.2688, -0.4253,  ..., -0.3436, -0.3910, -0.1638]],
       device='cuda:0')

In [79]:
def get_similar_tokens(query_token, k, model1=center_model, model2=context_model):
    W1 = model1.embed1.weight.data
    W2 = model2.embed1.weight.data
    # print(vocab_word_to_id[query_token])
    x1 = W1[vocab_word_to_id[query_token]]
    x2 = W2[vocab_word_to_id[query_token]]
    x = (x1 + x2) / 2
    # Compute the cosine similarity. Add 1e-9 for numerical stability
    # torch.mv : Performs a matrix-vector product of the matrix input and the vector vec.
    cos = torch.mv(W1, x) / torch.sqrt(torch.sum(W1 * W1, dim=1) *
                                      (torch.sum(x * x) + 1e-9))
    topk = torch.topk(cos, k=k+1)[1].cpu().numpy().astype('int32')
    for i in topk[1:]:  # Remove the input words
        print(f'cosine sim={float(cos[i]):.3f}: {vocab_id_to_word[i]}')


get_similar_tokens('farm', 3)

cosine sim=0.336: horse
cosine sim=0.299: high-tech
cosine sim=0.289: excluding
