In [1]:
import torch
import torchvision

In [ ]:
dataset = torchvision.datasets.MNIST(root = '/home/tian/Projects/d2l/data', transform=torchvision.transforms.ToTensor())

In [2]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [5]:
class WineDataset(Dataset):

    def __init__(self, transform=None):
        # data loading
        # using , to split the data, skip the row 1 because it is the title
        xy = np.loadtxt("/home/tian/Projects/d2l/data/wine.csv", delimiter=",", dtype=np.float32, skiprows=1)
        # column 0 is the classes, the input should be those features in column[1:]
        # self.x = torch.from_numpy(xy[:, 1:])
        self.x = xy[:, 1:]
        # self.y = torch.from_numpy(xy[:, [0]]) # size = n_sample, 1
        self.y = xy[:, [0]]

        self.transform = transform


    def __getitem__(self, index):
        # dataset[0]
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)

        return sample

    def __len__(self):
        # len(dataset)
        return self.n_samples


In [6]:
class ToTensor:
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [13]:
class MulTransform:
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        return inputs,targets

In [19]:
dataset = WineDataset(transform=ToTensor())

In [20]:
first_data = dataset[0]
features, labels = first_data
features, labels

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [23]:
composed = torchvision.transforms.Compose([ToTensor(),MulTransform(4)])
dataset_new = WineDataset(transform=composed)

In [24]:
first_data = dataset_new[0]
features, labels = first_data
features, labels

(tensor([5.6920e+01, 6.8400e+00, 9.7200e+00, 6.2400e+01, 5.0800e+02, 1.1200e+01,
         1.2240e+01, 1.1200e+00, 9.1600e+00, 2.2560e+01, 4.1600e+00, 1.5680e+01,
         4.2600e+03]),
 tensor([1.]))