In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [3]:
x = np.array([2.0, 1.0, 0.1])
softmax(x)

array([0.65900114, 0.24243297, 0.09856589])

In [7]:
y = torch.tensor([2.0, 1.0, 0.1])
torch.softmax(y, dim=0)

tensor([0.6590, 0.2424, 0.0986])

In [8]:
def corss_entropy(actual, predicted):
    loss = -np.sum(actual * np.log(predicted))
    return loss

In [9]:
label = np.array([1, 0, 0])
pred_good = np.array([0.7, 0.2, 0.1])
pred_bad = np.array([0.2, 0.6, 0.2])

In [10]:
print(corss_entropy(label, pred_good))
print(corss_entropy(label, pred_bad))

0.35667494393873245
1.6094379124341003


In [20]:
"""nn.CrossEntropyLoss already has softmax within
Y should be class labels, not ont-hot
Y-pred should has raw scores, no softmax"""

loss = nn.CrossEntropyLoss()
# 3 samples
Y = torch.tensor([2, 0, 1])
# assuming 1 sample, 3 possible classes
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])

Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 3.0, 0.1]])



In [21]:
l1 = loss(Y_pred_good,Y)
l2 = loss(Y_pred_bad,Y)

print(l1.item())
print(l2.item())

0.3018244206905365
1.6241613626480103


In [22]:
_, pred1 = torch.max(Y_pred_good, 1)
_, pred2 = torch.max(Y_pred_bad, 1)

In [23]:
pred1, pred2

(tensor([2, 0, 1]), tensor([0, 2, 1]))